package Question2;

import java.util.ArrayList;

/* 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

public class Q2 {

	public static void main(String[] args) {

		ArrayList<Integer> numbers = new ArrayList<Integer>();
		int limit = 4000000;
		int sum = 0;

		numbers = startFibonacci(limit);

		sum = sumNumbersList(numbers);

		System.out.println("Result: " + sum);
	}

	private static ArrayList<Integer> startFibonacci(int limit) {

		ArrayList<Integer> listNumbers = new ArrayList<Integer>();

		int number1 = 0;
		int number2 = 1;
		int numCalc = 0;

		while (numCalc < limit) {

			numCalc = number1 + number2;

			if (numCalc < limit && numCalc % 2 == 0) {

				listNumbers.add(numCalc);
			}

			number1 = number2;
			number2 = numCalc;
		}

		return listNumbers;
	}

	private static int sumNumbersList(ArrayList<Integer> numbers) {

		int sum = 0;

		for (Integer number : numbers) {

			sum += number;
		}

		return sum;
	}

}
